name: Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      LICENSE_SIGNING_KEY: ${{ secrets.LICENSE_SIGNING_KEY }}
      PORT: ${{ secrets.PORT }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./tarpaulin-report.xml
          token: ${{ secrets.CODECOV_TOKEN }}