name: Coverage

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      LICENSE_SIGNING_KEY: ${{ secrets.LICENSE_SIGNING_KEY }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v4.2.1
        with:
          egress-policy: audit

      - name: Checkout code with submodules
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive  # This is the key fix!

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          files: ./tarpaulin-report.xml
          token: ${{ secrets.CODECOV_TOKEN }}