name: Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.80.0]

    env:
      CARGO_HOME: /usr/local/cargo
      PATH: /usr/local/cargo/bin:$PATH  
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RUST_LOG: info
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v3

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./tarpaulin-report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
