name: Publish Docker image to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # e.g., v1.2.3

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code with submodules
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Log in to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag
        id: vars
        run: |
          echo "TAG=latest" >> $GITHUB_OUTPUT
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
            echo "TAG=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            LICENSE_SIGNING_KEY=${{ secrets.LICENSE_SIGNING_KEY }}
            PORT=${{ secrets.PORT }}
            FIPS_MODE=false
            FIPS_VALIDATION=false
          tags: |
            ghcr.io/atelier-logos/nabla:latest
            ghcr.io/atelier-logos/nabla:${{ steps.vars.outputs.TAG }}

      - name: Build and push FIPS Docker image
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            LICENSE_SIGNING_KEY=${{ secrets.LICENSE_SIGNING_KEY }}
            PORT=${{ secrets.PORT }}
            FIPS_MODE=true
            FIPS_VALIDATION=true
          tags: |
            ghcr.io/atelier-logos/nabla-enterprise:latest
            ghcr.io/atelier-logos/nabla-enterprise:${{ steps.vars.outputs.TAG }}
